import {
  Patient,
  ChecklistItem,
  FamilyPhotoItem,
  SituationScenario,
  CaregiverNote,
  CaregiverUser,
  DoctorUser,
  UserAccount,
} from './types';

export const INITIAL_CAREGIVERS: CaregiverUser[] = [
  {
    id: 'care-1',
    name: 'Ananya Saikia',
    relation: 'Daughter',
    phone: '+91 98640-12345',
    email: 'ananya@projectoctave.org',
    patientId: 'pat-1',
  },
  {
    id: 'care-2',
    name: 'Tomba Meitei',
    relation: 'Son',
    phone: '+91 98560-54321',
    email: 'tomba@projectoctave.org',
    patientId: 'pat-2',
  },
  {
    id: 'care-3',
    name: 'Arenla Longchar',
    relation: 'Daughter',
    phone: '+91 94360-77889',
    email: 'arenla@projectoctave.org',
    patientId: 'pat-3',
  },
  {
    id: 'care-4',
    name: 'Debabrata Debbarma',
    relation: 'Son',
    phone: '+91 94361-11223',
    email: 'debabrata@projectoctave.org',
    patientId: 'pat-4',
  },
];

export const INITIAL_DOCTORS: DoctorUser[] = [
  {
    id: 'doc-1',
    name: 'Dr. Pranab Baruah, MD (Neurology)',
    qualification: 'MD (Neurology), AIIMS New Delhi',
    hospital: 'Guwahati Neurological Institute (Assam)',
    assignedPatientIds: ['pat-1', 'pat-2', 'pat-3', 'pat-4'],
  },
  {
    id: 'doc-2',
    name: 'Dr. Lalthanzauva Sailo, MBBS, DNB',
    qualification: 'MBBS, DNB (Family Medicine)',
    hospital: 'Aizawl Regional Tele-Health Centre (Mizoram)',
    assignedPatientIds: ['pat-1', 'pat-3'],
  },
  {
    id: 'doc-3',
    name: 'Dr. Ibotombi Sharma, MD',
    qualification: 'MD (Geriatrics), RIMS Imphal',
    hospital: 'Imphal Valley Memory Clinic (Manipur)',
    assignedPatientIds: ['pat-2'],
  },
];

export const MOCK_ACCOUNTS: UserAccount[] = [
  // 1. Medical Doctors
  {
    id: 'user-doc-1',
    email: 'dr.baruah@projectoctave.org',
    password: 'doctor123',
    role: 'doctor',
    name: 'Dr. Pranab Baruah, MD (Assam)',
    doctorId: 'doc-1',
  },
  {
    id: 'user-doc-2',
    email: 'dr.sailo@projectoctave.org',
    password: 'doctor123',
    role: 'doctor',
    name: 'Dr. Lalthanzauva Sailo, MBBS (Mizoram)',
    doctorId: 'doc-2',
  },
  {
    id: 'user-doc-3',
    email: 'dr.sharma@projectoctave.org',
    password: 'doctor123',
    role: 'doctor',
    name: 'Dr. Ibotombi Sharma, MD (Manipur)',
    doctorId: 'doc-3',
  },
  // 2. Family Caregivers
  {
    id: 'user-care-1',
    email: 'ananya@projectoctave.org',
    password: 'caregiver123',
    role: 'caregiver',
    name: 'Ananya Saikia (Daughter - Assam)',
    caregiverId: 'care-1',
    patientId: 'pat-1',
  },
  {
    id: 'user-care-2',
    email: 'tomba@projectoctave.org',
    password: 'caregiver123',
    role: 'caregiver',
    name: 'Tomba Meitei (Son - Manipur)',
    caregiverId: 'care-2',
    patientId: 'pat-2',
  },
  {
    id: 'user-care-3',
    email: 'arenla@projectoctave.org',
    password: 'caregiver123',
    role: 'caregiver',
    name: 'Arenla Longchar (Daughter - Nagaland)',
    caregiverId: 'care-3',
    patientId: 'pat-3',
  },
  {
    id: 'user-care-4',
    email: 'debabrata@projectoctave.org',
    password: 'caregiver123',
    role: 'caregiver',
    name: 'Debabrata Debbarma (Son - Tripura)',
    caregiverId: 'care-4',
    patientId: 'pat-4',
  },
  // 3. Elders / Patients
  {
    id: 'user-pat-1',
    email: 'bhaben@projectoctave.org',
    password: 'patient123',
    accessCode: 'BHABEN74',
    role: 'patient',
    name: 'Bhaben Kalita (Assam)',
    patientId: 'pat-1',
  },
  {
    id: 'user-pat-2',
    email: 'shanti@projectoctave.org',
    password: 'patient123',
    accessCode: 'SHANTI69',
    role: 'patient',
    name: 'Shanti Devi (Manipur)',
    patientId: 'pat-2',
  },
  {
    id: 'user-pat-3',
    email: 'temsu@projectoctave.org',
    password: 'patient123',
    accessCode: 'TEMSU72',
    role: 'patient',
    name: 'Temsuwati Ao (Nagaland)',
    patientId: 'pat-3',
  },
  {
    id: 'user-pat-4',
    email: 'biren@projectoctave.org',
    password: 'patient123',
    accessCode: 'BIREN78',
    role: 'patient',
    name: 'Birendra Debbarma (Tripura)',
    patientId: 'pat-4',
  },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'pat-1',
    name: 'Bhaben Kalita',
    age: 74,
    location: 'Kamrup Metro, Guwahati',
    stateNE: 'Assam',
    stage: 'Stage 2 (Moderate Impairment)',
    riskLevel: 'Monitoring',
    avatarSeed: 'bhaben',
    engagementScore: 84,
    memoryAccuracy: 78,
    adherenceRate: 92,
    trend30Days: [68, 70, 72, 69, 74, 75, 71, 73, 76, 78, 77, 79, 81, 80, 82, 84, 83, 85, 82, 84, 86, 85, 87, 86, 88, 85, 87, 89, 88, 90],
    linkedCaregiverId: 'care-1',
    linkedDoctorIds: ['doc-1', 'doc-2'],
    emergencyContact: {
      name: 'Ananya Saikia',
      relation: 'Daughter (Primary Caregiver)',
      phone: '+91 98640-12345',
      secondaryPhone: '+91 98640-67890',
    },
    emergencyNotes: 'Allergic to penicillin. Enjoys morning Ronga Saah. Needs warm amber lighting after 5 PM to alleviate sundowning.',
    sharingPermissions: {
      caregivers: {
        'care-1': true,
        'care-2': false,
      },
      doctors: {
        'doc-1': true,
        'doc-2': false,
      },
    },
    clinicalNotes: [
      {
        id: 'cn-1',
        patientId: 'pat-1',
        author: 'Dr. Pranab Baruah, MD',
        date: 'Yesterday, 4:30 PM',
        category: 'Cognitive Metric',
        text: 'Patient recognized daughter Ananya and grandson Amit on first attempt in photo quiz. Response latency improved by 1.8 seconds over baseline.',
      },
      {
        id: 'cn-2',
        patientId: 'pat-1',
        author: 'Dr. Pranab Baruah, MD',
        date: '3 days ago',
        category: 'Medication',
        text: 'Maintained Donepezil 5mg with breakfast. Caregiver reports steady sleep continuity in the morning hours.',
      },
    ],
  },
  {
    id: 'pat-2',
    name: 'Shanti Devi',
    age: 69,
    location: 'Imphal West',
    stateNE: 'Manipur',
    stage: 'Stage 1 (Mild Forgetfulness)',
    riskLevel: 'Stable',
    avatarSeed: 'shanti',
    engagementScore: 92,
    memoryAccuracy: 88,
    adherenceRate: 96,
    trend30Days: [75, 77, 78, 80, 82, 81, 83, 85, 84, 86, 87, 89, 88, 90, 89, 91, 92, 90, 93, 91, 94, 93, 95, 94, 92, 95, 96, 94, 95, 96],
    linkedCaregiverId: 'care-2',
    linkedDoctorIds: ['doc-1', 'doc-3'],
    emergencyContact: {
      name: 'Tomba Meitei',
      relation: 'Son (Primary Caregiver)',
      phone: '+91 98560-54321',
      secondaryPhone: '+91 98560-98765',
    },
    emergencyNotes: 'Prefers Meitei language audio cues for memory recall. Regular blood pressure check after breakfast.',
    sharingPermissions: {
      caregivers: {
        'care-1': false,
        'care-2': true,
      },
      doctors: {
        'doc-1': true,
        'doc-2': false,
        'doc-3': true,
      },
    },
    clinicalNotes: [
      {
        id: 'cn-3',
        patientId: 'pat-2',
        author: 'Dr. Pranab Baruah, MD',
        date: '2 days ago',
        category: 'Observation',
        text: 'High engagement with Loktak lotus and heritage symbols. Very alert during morning family discussions.',
      },
    ],
  },
  {
    id: 'pat-3',
    name: 'Temsuwati Ao',
    age: 72,
    location: 'Mokokchung / Kohima',
    stateNE: 'Nagaland',
    stage: 'Stage 1 (Mild Cognitive Signs)',
    riskLevel: 'Stable',
    avatarSeed: 'temsu',
    engagementScore: 89,
    memoryAccuracy: 85,
    adherenceRate: 94,
    trend30Days: [70, 72, 74, 75, 78, 77, 79, 81, 80, 83, 82, 85, 84, 86, 85, 87, 89, 88, 90, 89, 91, 90, 92, 93, 91, 94, 93, 95, 94, 96],
    linkedCaregiverId: 'care-3',
    linkedDoctorIds: ['doc-1', 'doc-2'],
    emergencyContact: {
      name: 'Arenla Longchar',
      relation: 'Daughter',
      phone: '+91 94360-77889',
    },
    emergencyNotes: 'Excellent physical agility on hill paths. Daily walks in community grounds. Mild left ear hearing loss.',
    sharingPermissions: {
      caregivers: {
        'care-1': false,
        'care-2': false,
        'care-3': true,
      },
      doctors: {
        'doc-1': true,
        'doc-2': true,
      },
    },
    clinicalNotes: [
      {
        id: 'cn-5',
        patientId: 'pat-3',
        author: 'Dr. Pranab Baruah, MD',
        date: '1 week ago',
        category: 'Cognitive Metric',
        text: 'Excellent spatial retention in symbol matching. Continues daily brisk walking in community church grounds.',
      },
    ],
  },
  {
    id: 'pat-4',
    name: 'Birendra Debbarma',
    age: 78,
    location: 'Agartala, West Tripura',
    stateNE: 'Tripura',
    stage: 'Stage 2 (Moderate Decline)',
    riskLevel: 'Attention Required',
    avatarSeed: 'birendra',
    engagementScore: 68,
    memoryAccuracy: 64,
    adherenceRate: 75,
    trend30Days: [72, 70, 68, 69, 67, 65, 66, 68, 65, 64, 66, 65, 63, 62, 64, 65, 63, 62, 64, 65, 66, 64, 65, 67, 66, 65, 68, 67, 69, 70],
    linkedCaregiverId: 'care-4',
    linkedDoctorIds: ['doc-1'],
    emergencyContact: {
      name: 'Debabrata Debbarma',
      relation: 'Son',
      phone: '+91 94361-11223',
    },
    emergencyNotes: 'Sundowning symptoms noticeable around 4:30 PM. Keep verandah brightly lit.',
    sharingPermissions: {
      caregivers: {
        'care-1': false,
        'care-4': true,
      },
      doctors: {
        'doc-1': true,
        'doc-2': false,
      },
    },
    clinicalNotes: [
      {
        id: 'cn-4',
        patientId: 'pat-4',
        author: 'Dr. Pranab Baruah, MD',
        date: '5 days ago',
        category: 'Family Update',
        text: 'Caregiver alerted to afternoon sundowning symptoms. Advised keeping verandah well lit with warm amber lighting after 4:30 PM.',
      },
    ],
  },
];

export const INITIAL_CHECKLIST: ChecklistItem[] = [
  {
    id: 'chk-1',
    labelKey: 'taskMorningMeds',
    time: '08:00 AM',
    category: 'medicine',
    completed: true,
  },
  {
    id: 'chk-2',
    labelKey: 'taskHydration',
    time: '10:30 AM',
    category: 'hydration',
    completed: true,
  },
  {
    id: 'chk-3',
    labelKey: 'taskNutritiousMeal',
    time: '01:00 PM',
    category: 'meal',
    completed: false,
  },
  {
    id: 'chk-4',
    labelKey: 'taskGentleWalk',
    time: '04:00 PM',
    category: 'activity',
    completed: false,
  },
  {
    id: 'chk-5',
    labelKey: 'taskEveningTea',
    time: '05:30 PM',
    category: 'hydration',
    completed: false,
  },
  {
    id: 'chk-6',
    labelKey: 'taskNightRest',
    time: '09:00 PM',
    category: 'sleep',
    completed: false,
  },
];

// Curated high-contrast family photo items
export const INITIAL_FAMILY_PHOTOS: FamilyPhotoItem[] = [
  {
    id: 'fam-1',
    name: 'Rahul',
    relation: 'Son (Rahul)',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80',
    correctAnswer: true,
  },
  {
    id: 'fam-2',
    name: 'Ananya',
    relation: 'Daughter (Ananya)',
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80',
    correctAnswer: true,
  },
  {
    id: 'fam-3',
    name: 'Priya',
    relation: 'Granddaughter (Priya)',
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
    correctAnswer: true,
  },
  {
    id: 'fam-4',
    name: 'Amit',
    relation: 'Grandson (Amit)',
    imageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600&auto=format&fit=crop&q=80',
    correctAnswer: true,
  },
];

export const INITIAL_CAREGIVER_NOTES: CaregiverNote[] = [
  {
    id: 'cnote-1',
    timestamp: 'Today, 10:15 AM',
    text: 'Ate a wholesome bowl of warm khichdi and fresh seasonal greens with great appetite. Smiled warmly while looking at grandson Amit\'s school photo.',
    category: 'Appetite',
    notifiedDoctor: true,
  },
  {
    id: 'cnote-2',
    timestamp: 'Yesterday, 8:45 PM',
    text: 'Slept peacefully throughout the night after warm ginger-tulsi tea. No signs of disorientation or night wandering.',
    category: 'Sleep',
    notifiedDoctor: false,
  },
  {
    id: 'cnote-3',
    timestamp: '2 days ago',
    text: 'Enjoyed listening to folk songs on the radio on the verandah. Memory of old Guwahati market was lucid and vivid.',
    category: 'Mood',
    notifiedDoctor: true,
  },
];

// REGION-SPECIFIC DEMENTIA & SAFETY QUICK REACTION TESTS (5 Questions per State)
export const REGIONAL_SITUATION_SCENARIOS: Record<string, SituationScenario[]> = {
  Assam: [
    {
      id: 'as-sit-1',
      region: 'Assam',
      scenarioType: 'safety',
      iconName: 'Flame',
      promptKey: 'situationPrompt1',
      promptText: 'It is 7:30 AM in your Assam home. The kettle is whistling for morning Ronga Saah (red tea). What should you do first?',
      optionA: {
        labelKey: 'asSitOption1A',
        text: 'Safely turn off the gas stove with a dry cloth before pouring',
        isCorrect: true,
        icon: 'Flame',
      },
      optionB: {
        labelKey: 'asSitOption1B',
        text: 'Touch the red-hot burner with bare wet fingers',
        isCorrect: false,
        icon: 'AlertTriangle',
      },
    },
    {
      id: 'as-sit-2',
      region: 'Assam',
      scenarioType: 'weather',
      iconName: 'Umbrella',
      promptKey: 'situationPrompt2',
      promptText: 'Sudden monsoon rain has started in Kamrup. You need to step outside to the local Namghar / bazaar. What should you take?',
      optionA: {
        labelKey: 'asSitOption2A',
        text: 'Take your big umbrella (Chhati) and wear non-slip sandals',
        isCorrect: true,
        icon: 'Umbrella',
      },
      optionB: {
        labelKey: 'asSitOption2B',
        text: 'Walk barefoot on the slippery red clay mud by the road',
        isCorrect: false,
        icon: 'Footprints',
      },
    },
    {
      id: 'as-sit-3',
      region: 'Assam',
      scenarioType: 'health',
      iconName: 'Bed',
      promptKey: 'situationPrompt3',
      promptText: 'After lunch, the afternoon heat in Guwahati is rising. Your eyes feel tired and heavy. What is the safest choice?',
      optionA: {
        labelKey: 'asSitOption3A',
        text: 'Drink a glass of water and rest comfortably on your cool bed',
        isCorrect: true,
        icon: 'Bed',
      },
      optionB: {
        labelKey: 'asSitOption3B',
        text: 'Walk into direct scorching sun on the highway without a hat',
        isCorrect: false,
        icon: 'Sun',
      },
    },
    {
      id: 'as-sit-4',
      region: 'Assam',
      scenarioType: 'health',
      iconName: 'GlassWater',
      promptKey: 'situationPrompt4',
      promptText: 'Your caregiver placed your morning Donepezil tablet next to your glass of water on the table. What should you do?',
      optionA: {
        labelKey: 'asSitOption4A',
        text: 'Take the tablet with a full glass of water as usual',
        isCorrect: true,
        icon: 'GlassWater',
      },
      optionB: {
        labelKey: 'asSitOption4B',
        text: 'Skip the tablet since you already had morning Ronga Saah',
        isCorrect: false,
        icon: 'AlertTriangle',
      },
    },
    {
      id: 'as-sit-5',
      region: 'Assam',
      scenarioType: 'safety',
      iconName: 'DoorClosed',
      promptKey: 'situationPrompt5',
      promptText: 'It is evening Bihu time and you hear someone knocking at your front door. You do not recognize the voice. What should you do?',
      optionA: {
        labelKey: 'asSitOption5A',
        text: 'Call out to ask who it is and wait for your caregiver before opening',
        isCorrect: true,
        icon: 'ShieldCheck',
      },
      optionB: {
        labelKey: 'asSitOption5B',
        text: 'Immediately open the door wide to any unknown stranger',
        isCorrect: false,
        icon: 'AlertTriangle',
      },
    },
  ],

  Nagaland: [
    {
      id: 'nag-sit-1',
      region: 'Nagaland',
      scenarioType: 'safety',
      iconName: 'Footprints',
      promptKey: 'situationPrompt1',
      promptText: 'You are stepping out for a morning walk in Mokokchung / Kohima on a misty, steep hill slope. How should you step?',
      optionA: {
        labelKey: 'nagSitOption1A',
        text: 'Wear firm grip shoes and lean on your bamboo walking cane',
        isCorrect: true,
        icon: 'Footprints',
      },
      optionB: {
        labelKey: 'nagSitOption1B',
        text: 'Wear smooth flat plastic slippers on the wet steep slope',
        isCorrect: false,
        icon: 'AlertTriangle',
      },
    },
    {
      id: 'nag-sit-2',
      region: 'Nagaland',
      scenarioType: 'safety',
      iconName: 'Wind',
      promptKey: 'situationPrompt2',
      promptText: 'In the traditional kitchen, firewood in the hearth (Meka) is smoking heavily. What should you do right away?',
      optionA: {
        labelKey: 'nagSitOption2A',
        text: 'Open the wooden window slit to let the smoke vent outside safely',
        isCorrect: true,
        icon: 'Wind',
      },
      optionB: {
        labelKey: 'nagSitOption2B',
        text: 'Shut all doors and windows tightly and breathe in the dense smoke',
        isCorrect: false,
        icon: 'DoorClosed',
      },
    },
    {
      id: 'nag-sit-3',
      region: 'Nagaland',
      scenarioType: 'health',
      iconName: 'Sparkles',
      promptKey: 'situationPrompt3',
      promptText: 'The sun has set behind the Naga hills and cold mountain wind is blowing through the porch. What should you do?',
      optionA: {
        labelKey: 'nagSitOption3A',
        text: 'Wrap your warm Naga woolen shawl and sip hot boiled water indoors',
        isCorrect: true,
        icon: 'Sparkles',
      },
      optionB: {
        labelKey: 'nagSitOption3B',
        text: 'Sit outside in a thin vest directly in the freezing mountain wind',
        isCorrect: false,
        icon: 'Wind',
      },
    },
    {
      id: 'nag-sit-4',
      region: 'Nagaland',
      scenarioType: 'health',
      iconName: 'GlassWater',
      promptKey: 'situationPrompt4',
      promptText: 'After eating your morning meal of Galho (rice porridge) in Dimapur, your mouth feels very dry. What is the right thing to do?',
      optionA: {
        labelKey: 'nagSitOption4A',
        text: 'Drink a clean cup of boiled or filtered water slowly',
        isCorrect: true,
        icon: 'GlassWater',
      },
      optionB: {
        labelKey: 'nagSitOption4B',
        text: 'Drink unfiltered rainwater collected in the open barrel outside',
        isCorrect: false,
        icon: 'AlertTriangle',
      },
    },
    {
      id: 'nag-sit-5',
      region: 'Nagaland',
      scenarioType: 'safety',
      iconName: 'Flame',
      promptKey: 'situationPrompt5',
      promptText: 'During the Hornbill Festival week, a kerosene lamp is left burning on your wooden table. You are going to sleep. What should you do?',
      optionA: {
        labelKey: 'nagSitOption5A',
        text: 'Blow out the lamp carefully and place it on the stone floor before sleeping',
        isCorrect: true,
        icon: 'Flame',
      },
      optionB: {
        labelKey: 'nagSitOption5B',
        text: 'Leave the lamp burning on the wooden table through the night',
        isCorrect: false,
        icon: 'AlertTriangle',
      },
    },
  ],

  Manipur: [
    {
      id: 'mni-sit-1',
      region: 'Manipur',
      scenarioType: 'safety',
      iconName: 'Footprints',
      promptKey: 'situationPrompt1',
      promptText: 'Monsoon showers have left the courtyard stones in Imphal covered with green moss. How should you walk outside?',
      optionA: {
        labelKey: 'mniSitOption1A',
        text: 'Hold the bamboo rail and place each foot deliberately and flatly',
        isCorrect: true,
        icon: 'Footprints',
      },
      optionB: {
        labelKey: 'mniSitOption1B',
        text: 'Run quickly across the moss without looking down',
        isCorrect: false,
        icon: 'AlertTriangle',
      },
    },
    {
      id: 'mni-sit-2',
      region: 'Manipur',
      scenarioType: 'safety',
      iconName: 'Flame',
      promptKey: 'situationPrompt2',
      promptText: 'Evening prayers at the Sanamahi prayer corner are finished. The oil lamp (Meira) is glowing. What is the safe step?',
      optionA: {
        labelKey: 'mniSitOption2A',
        text: 'Check that the lamp is stable and kept safely clear of hanging cloth',
        isCorrect: true,
        icon: 'Flame',
      },
      optionB: {
        labelKey: 'mniSitOption2B',
        text: 'Drape a dry cotton towel directly on top of the burning lamp',
        isCorrect: false,
        icon: 'AlertTriangle',
      },
    },
    {
      id: 'mni-sit-3',
      region: 'Manipur',
      scenarioType: 'health',
      iconName: 'GlassWater',
      promptKey: 'situationPrompt3',
      promptText: 'You have finished your morning meal with warm Kanghou. Your throat feels dry. What should you drink?',
      optionA: {
        labelKey: 'mniSitOption3A',
        text: 'Drink a clean bell-metal glass of warm boiled water',
        isCorrect: true,
        icon: 'GlassWater',
      },
      optionB: {
        labelKey: 'mniSitOption3B',
        text: 'Avoid drinking any water for the entire day',
        isCorrect: false,
        icon: 'CupSoda',
      },
    },
    {
      id: 'mni-sit-4',
      region: 'Manipur',
      scenarioType: 'health',
      iconName: 'Sun',
      promptKey: 'situationPrompt4',
      promptText: 'You are visiting Loktak Lake with family. It is midday and very sunny. What should you carry?',
      optionA: {
        labelKey: 'mniSitOption4A',
        text: 'Wear your wide-brimmed hat and carry your water bottle',
        isCorrect: true,
        icon: 'Sun',
      },
      optionB: {
        labelKey: 'mniSitOption4B',
        text: 'Stand in the midday sun without a hat or water for two hours',
        isCorrect: false,
        icon: 'AlertTriangle',
      },
    },
    {
      id: 'mni-sit-5',
      region: 'Manipur',
      scenarioType: 'safety',
      iconName: 'Bed',
      promptKey: 'situationPrompt5',
      promptText: 'At night in Imphal, the electricity has gone off (load-shedding). You want to use the bathroom. What is the safest step?',
      optionA: {
        labelKey: 'mniSitOption5A',
        text: 'Take your torch light and walk slowly holding the wall',
        isCorrect: true,
        icon: 'ShieldCheck',
      },
      optionB: {
        labelKey: 'mniSitOption5B',
        text: 'Run in full darkness across the room quickly',
        isCorrect: false,
        icon: 'AlertTriangle',
      },
    },
  ],

  Tripura: [
    {
      id: 'trp-sit-1',
      region: 'Tripura',
      scenarioType: 'safety',
      iconName: 'Footprints',
      promptKey: 'situationPrompt1',
      promptText: 'You are walking out into the courtyard in Agartala with morning dew on the bamboo walkway. How do you step?',
      optionA: {
        labelKey: 'trpSitOption1A',
        text: 'Step carefully along the dry central path with rubber sandals',
        isCorrect: true,
        icon: 'Footprints',
      },
      optionB: {
        labelKey: 'trpSitOption1B',
        text: 'Run fast across the wet slippery bamboo poles',
        isCorrect: false,
        icon: 'AlertTriangle',
      },
    },
    {
      id: 'trp-sit-2',
      region: 'Tripura',
      scenarioType: 'health',
      iconName: 'Sun',
      promptKey: 'situationPrompt2',
      promptText: 'At 5:00 PM the sun sets quickly in Tripura. The verandah gets dark and shadows look confusing (sundowning). What should you do?',
      optionA: {
        labelKey: 'trpSitOption2A',
        text: 'Switch on the warm verandah lights and sit comfortably with family',
        isCorrect: true,
        icon: 'Sun',
      },
      optionB: {
        labelKey: 'trpSitOption2B',
        text: 'Sit alone in pitch darkness without turning on any lights',
        isCorrect: false,
        icon: 'DoorClosed',
      },
    },
    {
      id: 'trp-sit-3',
      region: 'Tripura',
      scenarioType: 'health',
      iconName: 'GlassWater',
      promptKey: 'situationPrompt3',
      promptText: 'Your caregiver has placed your morning tablet with a cup on the dining table. What should you do?',
      optionA: {
        labelKey: 'trpSitOption3A',
        text: 'Take the morning tablet with a full cup of fresh water',
        isCorrect: true,
        icon: 'GlassWater',
      },
      optionB: {
        labelKey: 'trpSitOption3B',
        text: 'Throw the tablet into the waste bin',
        isCorrect: false,
        icon: 'AlertTriangle',
      },
    },
    {
      id: 'trp-sit-4',
      region: 'Tripura',
      scenarioType: 'safety',
      iconName: 'Flame',
      promptKey: 'situationPrompt4',
      promptText: 'During Durga Puja celebrations in Agartala, a neighbour hands you a lighted diya (clay lamp). What should you do?',
      optionA: {
        labelKey: 'trpSitOption4A',
        text: 'Hold it carefully with both hands and place it steadily on the floor',
        isCorrect: true,
        icon: 'Flame',
      },
      optionB: {
        labelKey: 'trpSitOption4B',
        text: 'Carry it carelessly with one finger and wave it near curtains',
        isCorrect: false,
        icon: 'AlertTriangle',
      },
    },
    {
      id: 'trp-sit-5',
      region: 'Tripura',
      scenarioType: 'health',
      iconName: 'Bed',
      promptKey: 'situationPrompt5',
      promptText: 'After morning Mui Borok rice and vegetables, you feel dizzy. Your caregiver is in the next room. What is the first thing to do?',
      optionA: {
        labelKey: 'trpSitOption5A',
        text: 'Sit down immediately and call out to your caregiver for help',
        isCorrect: true,
        icon: 'ShieldCheck',
      },
      optionB: {
        labelKey: 'trpSitOption5B',
        text: 'Walk fast to the market alone without telling anyone',
        isCorrect: false,
        icon: 'AlertTriangle',
      },
    },
  ],
};

export const SITUATION_SCENARIOS: SituationScenario[] = REGIONAL_SITUATION_SCENARIOS.Assam;

